name: Craftvas
version: '0.5.0'
main: com.edwardshturman.craftvas.Craftvas
description: Integrate with the Canvas LMS
author: Edward Shturman
website: https://github.com/edwardshturman/craftvas
api-version: '1.21'
permissions:
  craftvas.meow:
    description: "Broadcast a meow"
    default: op
  craftvas.canvas:
    description: "Permission to interface with the Canvas API"
    default: op
commands:
  meow:
    description: "Broadcast a meow"
    usage: "/meow"
    permission: craftvas.meow
  canvas:
    description: "A set of utility commands for interfacing with the Canvas API"
    usage: "/canvas <info | url [url] | token [token]>"
    permission: craftvas.canvas
